version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: postgres-ai
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - JWT_SECRET=Tunglkce170271
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_EXPIRES_IN=7d
      - GEMINI_API_KEY=AIzaSyAz2MkM7Osi-J0XnlsKAw9mA8b2MdP7HXg
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - ./chinese_prompt.txt:/app/chinese_prompt.txt
      - ./korean_prompt.txt:/app/korean_prompt.txt
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
